import { Menu } from "@/common/components/Menu";
import "../styles/global.scss";

type AppLayoutProps = {
  children: React.ReactNode;
};

export const metadata = {
  title: "Layout Next.js title",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: AppLayoutProps) {
  return (
    <html lang="en">
      <body>
        <Menu />
        <main className="main-container"> {children}</main>
      </body>
    </html>
  );
}
